@page "/login"
@layout AuthLayout
@inject NavigationManager navigationManager
@inject CustomStateProvider authStateProvider

<h1 class="h2 font-weight-normal login-title">
    Login
</h1>

<EditForm class="form-signin" OnValidSubmit="@OnSubmit" Model="loginRequest">
    <DataAnnotationsValidator />

    <label for="inputUsername" class="sr-only">Kullanıcı Adı</label>
    <InputText id="inputUsername" class="form-control" @bind-Value="loginRequest.UserName" autofocus placeholder="Username" />
    <ValidationMessage For="@(() => loginRequest.UserName)" />

    <label for="inputPassword" class="sr-only">Şifre</label>
    <InputText type="password" id="inputPassword" class="form-control" placeholder="Password" @bind-Value="loginRequest.Password" />
    <ValidationMessage For="@(() => loginRequest.Password)" />

    <div class="form-check m-3">
        <InputCheckbox id="inputRememberMe" class="form-check-input" @bind-Value="@loginRequest.RememberMe" />
        <label class="form-check-label" for="inputRememberMe">Beni Hatırla</label>
    </div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Giriş</button>

    <label class="text-danger">@error</label>

    <NavLink href="register">
        <h6 class="font-weight-normal text-center">Hesap Oluştur</h6>
    </NavLink>
</EditForm>

@code{ 
    FaultApp2.Shared.Models.LoginRequest loginRequest { get; set; } = new FaultApp2.Shared.Models.LoginRequest();
            
    string error { get; set; }

           
    async Task OnSubmit()
            {
                error = null;
                try
                {
                 await authStateProvider.Login(loginRequest);
                 navigationManager.NavigateTo("fault");
                   
                }
                catch (Exception ex)
                {
                    error = ex.Message;
                    Console.WriteLine("ex", ex);
                }
            } 
    }